### ISSUE TITLE
Code for the examples in the gallery

### ISSUE THREAD

**Issue by book** [karlwilcox/drawshield-net#11]
Given the amount of things drawshield is capable of, learning from example is very useful. Sadly, the source code for the examples in the [gallery](https://drawshield.net/gallery/index.html) does not seems to be visible on the web site.

**Comment by karlwilcox** [comment]
Thanks for getting in touch. Apologies, this is not very clear. If you click on one of the small images in the gallery it brings up a lightbox with a larger image. Click on "More information" down at the bottom and it takes you to a page with the blazon and the big image. You can then "click here" at the bottom of that page which will take you straight to the "create" page with the blazon filled in.

I'll add some instructions to the gallery page soon!

**Comment by book** [comment]
So in fact, the issue is that in my version of Chrome, the bottom of the larger image is out of the viewport. I have to zoom out a lot for the bottom to show, and then the links are visible.

**Comment by karlwilcox** [comment]
Hmmm, what platform are you using? I can't seem to reproduce it on my deskstop unless I make the window really small. The website uses BootStrap 4 to do dynamic resizing, maybe I need to look again at the size breakpoints...?

**Comment by book** [comment]
I'm running Debian Linux:

    $ chromium --version
    Chromium 62.0.3202.89 built on Debian buster/sid, running on Debian buster/sid

**Comment by karlwilcox** [comment]
Thanks. I'm in a coffee shop at the moment ("Drawshield.net development is entirely powered by coffee and cake...") but when I get home I'll fire up a debian VM and take a look.

Cheers,
Karl

**Comment by karlwilcox** [comment]
Aha! Yes, I see it now, the BootStrap lightbox code is not calculating the right image dimensions on Debian. But I think this is my problem - the live site currently uses a locally hosted version of BootStrap-4-alpha. The next version uses the proper release, loaded from the cloudflare CDN so it should go away as soon I can get the next version live. I'm still working on the build system for it at the moment (I had to change the site generator to Hexo because Harp is no longer compatible with the latest version of Node.... Do you remember when building websites just involved typing HTML into Notepad++?)

So apologies, I will try to get this fixed as soon as possible. Thanks for reporting it,

Karl
